---
platforms:
  - name: ubuntu-16.04
    driver:
        vm_hostname: workshopbox.ws.p7-s.net
        gui: false
        box: pingworks_ubuntu-16.04_chef-12.7.2-1
        box_url: http://vagrant.pingworks.net/pingworks_ubuntu-16.04_chef-12.7.2-1.box
        #network:
        #  - ["forwarded_port", {guest: 80, host: 8080}]
suites:
  - name: default
    run_list:
      - recipe[workshopbox::default]
      - recipe[pw_testhelper::default]
    attributes:
      workshopbox:
      #  tweak:
      #    install_gnome_desktop: false
      #    reinstall_guest_additions: false
      #    install_docker: false
      #    install_kernmod_build_env: false
      #    install_atom_pkgs: false
      #    test_kitchen_docker: false
