---
platforms:
  - name: ubuntu-14.04
    driver:
        gui: false
        box: pingworks_ubuntu-14.04-desktop_chef-12.4.1-1
        box_url: http://vagrant.pingworks.net/pingworks_ubuntu-14.04-desktop_chef-12.4.1-1.box
        #network:
        #  - ["forwarded_port", {guest: 80, host: 8080}]
suites:
  - name: default
    run_list:
      - recipe[workshopbox::default]
      - recipe[pw_testhelper::default]
    attributes:
      workshopbox:
        workshop_name: __WORKSHOP_NAME__
         tweak:
           install_gnome_desktop: false # not longer needed (already installed in base image)
      #     reinstall_guest_additions: false
      #     install_docker: false
      #     install_kernmod_build_env: false
      #     install_atom_pkgs: false
      #     test_kitchen_docker: false
