---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: false

platforms:
  - name: ubuntu-14.04
    driver:
        gui: true
        box: pingworks_ubuntu-14.04_chef-12.4.1-1
        box_url: http://vagrant.pingworks.net/pingworks_ubuntu-14.04_chef-12.4.1-1

suites:
  - name: default
    run_list:
      - recipe[wsbox_base::default]
    attributes:

