---
driver:
  name: vagrant
  customize:
    memory: 4096
    vram: 64
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo
  require_chef_omnibus: false

platforms:
  - name: ubuntu-16.04
    driver:
        vm_hostname: workshopbox.ws.p7-s.net
        gui: true
        box: pingworks_ubuntu-16.04_chef-12.7.2-1
        box_url: http://vagrant.pingworks.net/pingworks_ubuntu-16.04_chef-12.7.2-1.box

suites:
  - name: default
    run_list:
      - recipe[workshopbox::default]
      #- recipe[secret_service::default]
    attributes:
