name 'workshopbox'
maintainer 'Alexander Birk'
maintainer_email 'birk@pingworks.de'
license 'Apache 2.0'
description 'Installs/Configures Workshopbox Appliance'
long_description 'Installs/Configures Workshopbox Appliance'
version '1.2.8'

depends 'apt', '~> 5.1.0'
depends 'ohai', '= 3.0.1'
depends 'secret_service', '~> 0.2.0'
depends 'pw_testhelper'
