name             'wsbox-base'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ws-wbox-base'
long_description 'Installs/Configures ws-wbox-base'
version          '0.1.0'

depends 'apt'
depends 'ohai'
